<?php

/**
 * @file
 * This module is an add-on to the FAQ module that allows users with the 'ask question'
 * permission to create a question which will be queued for an 'expert' to answer.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Mail\MailInterface;

/**
 * Implements hook_permission().
 *
 * Define the permissions this module uses
 *
 * @return array
 *   permissions defined for the faq_ask module
 */
function faq_ask_permission() {
  return array(
    'ask question' => array(
      'title' => t('Ask a question'),
      'description' => t('Ask a question to be submitted to an expert.'),
      ),
    'answer question' => array(
      'title' => t('Answer a question'),
      'description' => t('Answer a question submitted by someone asking.'),
      ),
    );
}

/**
 * Implements hook_node_submit()
 * 
 * Handle asking new question and answering.
 * 
 * @param \Drupal\node\NodeInterface $node 
 *   The node entity being updated in response to a form submission.
 * @param array $form
 *   The form being used to edit the node.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function faq_ask_node_submit(NodeInterface $node, $form, FormStateInterface $form_state){
  $faq_ask_settings = \Drupal::config('faq_ask.settings');

  //ask a new question
  if(true) {
    //register the node as unanswered question
    
    //handle notification to experts
    if($faq_ask_settings->get('notify_experts')) {

    }
    
  }
  //answering the question
  else {
    //delete the node from unanswered questions
    
    //handle notification to the asker
    if($faq_ask_settings->get('notify_asker')) {

    }
  }
  
}

/**
 * Implements hook_mail().
 * 
 * @param string $key
 *   An identifier of the mail.
 * @param array $message
 *   An array to be filled in.
 * @param array $params
 *   An array of parameters supplied by the caller of drupal_mail().
 */
function faq_ask_mail($key, &$message, $params) {
  // the mail sent when a new quesion is coming in
  if ($key == 'newquestion') {
    
  }
}